"""
Report Generation Agent - Uses LLM to produce human-readable verification reports
Explains WHY the document got its score and HOW the verdict was reached
"""

import os
from datetime import datetime
from typing import Dict, List, Optional
from pathlib import Path

from verification_engine.agent.llm import get_llm_client, get_llm_model


class ReportGenerationAgent:
    """
    AI Agent that generates human-readable verification reports using LLM
    Focuses on explaining the verification process, operations performed, and verdict reasoning
    """

    REPORT_PROMPT = """You are a professional Nigerian land document verification expert. 
Write a detailed, human-readable verification report explaining WHY this document received its score.

AUDIENCE: Bankers, lawyers, property buyers, and sellers in Nigeria
TONE: Professional, clear, educational - explain the verification process

REPORT STRUCTURE (use these headings):

# VERIFICATION REPORT: [Document Type]

## VERIFICATION SUMMARY
- Document ID and processing time
- Final Verdict: [LOW/MEDIUM/HIGH/CRITICAL] RISK
- Trust Score: [score]/100
- Action: [RELEASE_PAYMENT/HOLD_FUNDS_IN_ESCROW/BLOCK_PAYMENT]

## HOW WE VERIFIED THIS DOCUMENT
Explain the verification pipeline in simple terms:

### Stage 1: Document Intelligence (Zone-Aware OCR)
- What we did: Segmented document into zones (header, body, stamp zone, signature zone)
- Why this matters: Position tells us meaning (a name in header = issuer, name in body = owner)
- Results for this document: [what zones were found, stamp/signature detection]

### Stage 2: Vision Forensics (5 Checks)
Explain each check and what we found:
- **Error Level Analysis (ELA):** Detects Photoshop/editing artifacts - [PASS/FAIL]
- **Noise Consistency:** Detects copy-paste from different sources - [PASS/FAIL]  
- **Luminance Uniformity:** Detects assembly from multiple scans - [PASS/FAIL]
- **Edge Sharpness:** Detects pasted content with different sharpness - [PASS/FAIL]
- **Text Integrity:** Detects per-character compression anomalies - [PASS/FAIL]

### Stage 3: Offline Verification Tools (7 Forensic Checks)
Explain each tool's findings:
- **Reference Number Forensics:** [what was found / what was expected]
- **Date Logic Validation:** [any future dates? logical timeline?]
- **Template Matching:** [mandatory phrases present?]
- **Signature Verification:** [governor, commissioner, registrar found?]
- **Barcode Verification:** [security features present?]
- **Print/Scan Consistency:** [physical artifacts? digital characteristics?]
- **Image Provenance:** [metadata, DPI, editing software detected?]

## WHY THIS DOCUMENT SCORED [score]/100

Explain the calculation:
- Starting trust score: 95 (maximum possible)
- Deductions for each failed or warning check:
  - [Check name]: -[X] points because [reason]
  - [Check name]: -[X] points because [reason]
- Final score: [score]/100

## WHAT THIS MEANS FOR YOU

### For the Buyer:
- [Plain English advice based on risk level]

### For the Seller:
- [Plain English advice]

### For the Bank:
- **Action: [RELEASE_PAYMENT/HOLD_FUNDS_IN_ESCROW/BLOCK_PAYMENT]**
- [Specific instructions]

## VERDICT EXPLANATION

In plain English, tell the reader:
- Why the document received this risk level
- What specific findings drove the decision
- What confidence level we have in this assessment
- Any caveats or limitations

---
*This report was generated by Veritas AI Document Verification System.*

INPUT DATA:
{input_data}

Generate the report now. Use markdown formatting. Focus on EXPLAINING the verification process and WHY the score was given."""

    def __init__(self):
        self.client = get_llm_client()
        self.model = get_llm_model()

    def generate_report(self,
                        extracted_fields: Dict,
                        vision_forensics: Dict,
                        offline_verdict: Dict,
                        document_intelligence: Dict,
                        validation_warnings: List,
                        ocr_confidence: float,
                        processing_time: float,
                        document_name: str) -> str:
        """
        Generate a human-readable verification report explaining WHY
        """

                                        
        input_data = self._prepare_verification_explanation(
            extracted_fields,
            vision_forensics,
            offline_verdict,
            document_intelligence,
            validation_warnings,
            ocr_confidence,
            processing_time,
            document_name
        )

                  
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a Nigerian land document verification expert. Explain verification results clearly. Focus on WHY scores were given and WHAT operations were performed."},
                    {"role": "user", "content": self.REPORT_PROMPT.format(input_data=input_data)}
                ],
                temperature=0.3,
                max_tokens=2500
            )

            report = response.choices[0].message.content
            return report

        except Exception as e:
                                                  
            return self._generate_fallback_report(
                extracted_fields,
                vision_forensics,
                offline_verdict,
                validation_warnings,
                processing_time,
                document_name
            )

    def _prepare_verification_explanation(self,
                                           extracted_fields: Dict,
                                           vision_forensics: Dict,
                                           offline_verdict: Dict,
                                           document_intelligence: Dict,
                                           validation_warnings: List,
                                           ocr_confidence: float,
                                           processing_time: float,
                                           document_name: str) -> str:
        """Prepare structured input explaining verification results"""

        overall_risk = offline_verdict.get('overall_risk', 'MEDIUM')
        trust_score = offline_verdict.get('trust_score', 70)
        squad_action = offline_verdict.get('squad_action', 'HOLD_FUNDS_IN_ESCROW')
        total_weight = offline_verdict.get('total_suspicion_weight', 0)

                                                 
        deduction = 95 - trust_score

                               
        vision_checks = vision_forensics.get('checks', {})
        vision_results = []
        for check_name, check_data in vision_checks.items():
            vision_results.append({
                "name": check_name,
                "passed": not check_data.get('looks_wrong', False),
                "reason": check_data.get('reason', ''),
                "confidence": check_data.get('confidence', 0)
            })

                      
        tool_results = offline_verdict.get('tool_results', {})
        tool_summaries = []
        for tool_name, tool_result in tool_results.items():
            if tool_result:
                tool_summaries.append({
                    "name": tool_name,
                    "severity": tool_result.get('severity', 'PASS'),
                    "weight": tool_result.get('weight', 0),
                    "explanation": tool_result.get('explanation', '')
                })

                                           
        vision_deductions = sum(v.get('weight', 0) * 30 for v in vision_results if not v['passed'])
        tool_deductions = sum(t.get('weight', 0) * 40 for t in tool_summaries if t['severity'] not in ['PASS', 'LOW'])

        return f"""
=== VERIFICATION METADATA ===
Document Name: {document_name}
Processing Time: {processing_time:.1f} seconds
OCR Confidence: {ocr_confidence:.1%}

=== FINAL SCORES ===
Overall Risk: {overall_risk}
Trust Score: {trust_score}/100
Squad Action: {squad_action}
Total Suspicion Weight: {total_weight}
Total Deduction from Max (95): {deduction} points

=== DEDUCTION BREAKDOWN ===
Vision Forensics Deduction: ~{int(vision_deductions)} points
Offline Tools Deduction: ~{int(tool_deductions)} points
Field Extraction Deduction: ~{int(deduction - vision_deductions - tool_deductions)} points

=== STAGE 1: DOCUMENT INTELLIGENCE ===
Zones Detected: {document_intelligence.get('zones_found', [])}
Stamp Detected: {document_intelligence.get('stamp_detected', False)} (confidence: {document_intelligence.get('stamp_confidence', 0):.0%})
Signature Detected: {document_intelligence.get('signature_detected', False)}
Document Orientation: {document_intelligence.get('document_orientation', 0)}° corrected

=== STAGE 2: VISION FORENSICS (5 CHECKS) ===
{self._format_vision_results(vision_results)}

=== STAGE 3: OFFLINE VERIFICATION TOOLS ===
{self._format_tool_results(tool_summaries)}

=== EXTRACTED FIELDS ===
{self._format_extracted_fields(extracted_fields)}

=== VALIDATION WARNINGS ===
{chr(10).join([f"- {w}" for w in validation_warnings[:5]]) if validation_warnings else "- No warnings"}
"""

    def _format_vision_results(self, results: List) -> str:
        """Format vision results for prompt"""
        lines = []
        for r in results:
            status = "PASSED" if r['passed'] else "FAILED"
            lines.append(f"{r['name'].upper()}: {status}")
            lines.append(f"  Reason: {r['reason'][:150]}")
            lines.append(f"  Confidence: {r['confidence']:.0%}")
        return "\n".join(lines) if lines else "No vision checks performed"

    def _format_tool_results(self, results: List) -> str:
        """Format tool results for prompt"""
        lines = []
        for r in results:
            lines.append(f"{r['name']}: {r['severity']}")
            if r['explanation']:
                lines.append(f"  {r['explanation'][:150]}")
        return "\n".join(lines) if results else "No tool results available"

    def _format_extracted_fields(self, fields: Dict) -> str:
        """Format extracted fields"""
        lines = []
        for k, v in fields.items():
            if not k.startswith('_') and v:
                lines.append(f"- {k}: {str(v)[:80]}")
        return "\n".join(lines) if lines else "No fields extracted"

    def _generate_fallback_report(self,
                                   extracted_fields: Dict,
                                   vision_forensics: Dict,
                                   offline_verdict: Dict,
                                   validation_warnings: List,
                                   processing_time: float,
                                   document_name: str) -> str:
        """Fallback explanation report when LLM unavailable"""

        overall_risk = offline_verdict.get('overall_risk', 'MEDIUM')
        trust_score = offline_verdict.get('trust_score', 70)
        squad_action = offline_verdict.get('squad_action', 'HOLD_FUNDS_IN_ESCROW')
        deduction = 95 - trust_score

                             
        if overall_risk == "LOW":
            risk_icon = "🟢"
        elif overall_risk == "MEDIUM":
            risk_icon = "🟡"
        elif overall_risk == "HIGH":
            risk_icon = "🟠"
        else:
            risk_icon = "🔴"

        report = f"""# VERIFICATION REPORT: {document_name}

## VERIFICATION SUMMARY

{risk_icon} **Final Verdict: {overall_risk} RISK**
**Trust Score: {trust_score}/100** (Deducted {deduction} points from maximum 95)
**Action: {squad_action}**
**Processing Time: {processing_time:.1f} seconds**

## HOW WE VERIFIED THIS DOCUMENT

We performed a 3-stage verification process:

### Stage 1: Document Intelligence (Zone-Aware OCR)
- Segmented the document into structural zones (header, body, stamp zone, signature zone)
- Detected official stamp: {'✅ Yes' if vision_forensics.get('stamp_detected') else '❌ No'}
- Detected signature: {'✅ Yes' if vision_forensics.get('signature_detected') else '❌ No'}

### Stage 2: Vision Forensics (5 Checks)
We ran 5 forensic checks to detect visual manipulation:

| Check | What It Detects | Result |
|-------|-----------------|--------|
| ELA | Photoshop/editing artifacts | {'✅ PASS' if not vision_forensics.get('checks', {}).get('ela', {}).get('looks_wrong') else '❌ FAIL'} |
| Noise | Copy-paste from different sources | {'✅ PASS' if not vision_forensics.get('checks', {}).get('noise', {}).get('looks_wrong') else '❌ FAIL'} |
| Luminance | Assembly from multiple scans | {'✅ PASS' if not vision_forensics.get('checks', {}).get('luminance', {}).get('looks_wrong') else '❌ FAIL'} |
| Edge | Pasted content sharpness mismatch | {'✅ PASS' if not vision_forensics.get('checks', {}).get('edge', {}).get('looks_wrong') else '❌ FAIL'} |
| Text Integrity | Per-character compression anomalies | {'✅ PASS' if not vision_forensics.get('checks', {}).get('text_integrity', {}).get('looks_wrong') else '❌ FAIL'} |

### Stage 3: Offline Verification Tools (7 Forensic Checks)
We validated document content against known Nigerian government standards.

## WHY THIS DOCUMENT SCORED {trust_score}/100

**Starting trust score: 95** (maximum possible for any document)

**Deductions applied:**

"""

                                    
        if validation_warnings:
            report += f"- {len(validation_warnings)} validation warning(s): -{min(10, len(validation_warnings) * 3)} points\n"

        if not vision_forensics.get('stamp_detected'):
            report += "- Missing official stamp: -10 points\n"

        if not vision_forensics.get('signature_detected'):
            report += "- Missing signature: -5 points\n"

        report += f"""
**Final trust score: {trust_score}/100**

## WHAT THIS MEANS FOR YOU

### For the Buyer:
- {'⚠️ Do NOT make any payment. This document shows signs of fraud.' if overall_risk in ['HIGH', 'CRITICAL'] else '✅ Payment can proceed, but conduct standard due diligence.' if overall_risk == 'LOW' else '⚠️ Hold payment pending manual verification.'}

### For the Seller:
- {'Provide additional documentation to verify ownership.' if overall_risk in ['MEDIUM', 'HIGH', 'CRITICAL'] else 'Documentation appears complete.'}

### For the Bank:
- **Action: {squad_action}**
- {'Block payment immediately.' if squad_action == 'BLOCK_PAYMENT' else 'Hold funds in escrow pending manual review.' if squad_action == 'HOLD_FUNDS_IN_ESCROW' else 'Release payment.'}

## VERDICT EXPLANATION

{offline_verdict.get('recommendation', 'Manual review recommended.')}

**Confidence Level:** {'HIGH' if trust_score >= 80 else 'MEDIUM' if trust_score >= 60 else 'LOW'}

---
*This report was generated by Veritas AI Document Verification System.*
"""

        return report


def generate_verification_report(extracted_fields: Dict,
                                  vision_forensics: Dict,
                                  offline_verdict: Dict,
                                  document_intelligence: Dict,
                                  validation_warnings: List,
                                  ocr_confidence: float,
                                  processing_time: float,
                                  document_name: str) -> str:
    """
    Generate a human-readable verification report explaining WHY
    """
    agent = ReportGenerationAgent()
    return agent.generate_report(
        extracted_fields=extracted_fields,
        vision_forensics=vision_forensics,
        offline_verdict=offline_verdict,
        document_intelligence=document_intelligence,
        validation_warnings=validation_warnings,
        ocr_confidence=ocr_confidence,
        processing_time=processing_time,
        document_name=document_name
    )